name=mongo-forecast-outbox-connector
connector.class=com.mongodb.kafka.connect.MongoSourceConnector
connection.uri=mongodb://mongodb:27017/?replicaSet=rs0
database=forecast
collection=outboxevents
publish.full.document.only=true
topic.prefix=
topic.mapper=com.mongodb.kafka.connect.source.topic.mapping.StaticTopicMapper
topic.name=forecast-events
