name=mongo-user-outbox-connector
connector.class=com.mongodb.kafka.connect.MongoSourceConnector
connection.uri=mongodb://mongodb:27017/?replicaSet=rs0
database=user
collection=outboxevents
publish.full.document.only=true
topic.prefix=
topic.mapper=com.mongodb.kafka.connect.source.topic.mapping.StaticTopicMapper
topic.name=user
transforms=ExtractPayload
transforms.ExtractPayload.type=org.apache.kafka.connect.transforms.ExtractField$Value
transforms.ExtractPayload.field=payload
