bootstrap.servers=kafka:9092
key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false
offset.storage.file.filename=/data/connect.offsets
offset.flush.interval.ms=10000
rest.port=8083
rest.advertised.host.name=kafka-connect
rest.advertised.port=8083
plugin.path=/usr/share/java,/usr/share/confluent-hub-components
